// GENERATED by scripts/optimise-assets.mjs — do not edit by hand.
export interface Shot {
  src: string;
  srcSmall: string;
  width: number;
  height: number;
  blur: string;
}

export const SHOTS: Record<string, Shot> = {
  "today": {
    "src": "/shots/today.webp",
    "srcSmall": "/shots/today@small.webp",
    "width": 1080,
    "height": 2341,
    "blur": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQAwCdASoMABoAPu1iqU2ppaOiMAgBMB2JYgAASjC/b211qX0AAP7tcWcCnxRCQZ9xt5fLgh5jY8MYK5tNPyt6gC2y6YEFBfRtoL8KqWxqbzRUyIL5O2fl16E4QxifVda5OkrwGJVtwLi9shEnbwPYSHFjgOnsL8qF+AAA"
  },
  "browse": {
    "src": "/shots/browse.webp",
    "srcSmall": "/shots/browse@small.webp",
    "width": 1080,
    "height": 2341,
    "blur": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoMABoAPu1iqk2ppaQiMAgBMB2JZwADWACxS0Ws7UkAAP7v0cPc6Jm3+DasTA4bnAEMPB68jikUDBTIIRtcHv7UtcQXh4Y9rmPexy12zAwX7lmsGPMXTKjN1kDolklAAAA="
  },
  "saved": {
    "src": "/shots/saved.webp",
    "srcSmall": "/shots/saved@small.webp",
    "width": 1080,
    "height": 2341,
    "blur": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAABwAwCdASoMABoAPu1iqU2ppaQiMAgBMB2JZwAASmiZR0VyUAAA/u/Rw9zombf1GKMFJQFsaRcFeiVjZZp3+sn7NukWh203rsjHAAAA"
  },
  "settings": {
    "src": "/shots/settings.webp",
    "srcSmall": "/shots/settings@small.webp",
    "width": 1080,
    "height": 2341,
    "blur": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoMABoAPu1iqU2ppaOiMAgBMB2JZQC7ABrfMHZ0D20lfvCgAP7v0cPc6Jm3+Bhs7CBQx14suVnQYKRYvo0yiOofVXr+u5N3Vo3rr7TSS0Bf7gwrCZxZu2HUf8w8+jYd2lQMTjZAAAA="
  },
  "widgetHome": {
    "src": "/shots/widgetHome.webp",
    "srcSmall": "/shots/widgetHome@small.webp",
    "width": 1080,
    "height": 2341,
    "blur": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQAwCdASoMABoAPu1iqU2ppaOiMAgBMB2JZAC06CHVE/MN19pPjJAA/tD7DjFGxPITNVBuMvOk+E/GiNdjwnA7r1IgbPf1jIJqnBQFnXN1XC2stW6KSWIC6GrCLJE5OdsYTTCaBn1BnQ0CVCwk+TOV9JXLDcfxSnhWcPtaB+wfR4F0K1bXx20AAAA="
  }
};
