// GENERATED by scripts/build-words.mjs — do not edit by hand.
// Source: the Yumo app's assets/word-data.json (7,972 records).
import type { Level } from './tokens';
import type { SiteWord } from './select-words';

export const WORDS: SiteWord[] = [
  {
    "id": 6,
    "kanji": "赤い",
    "kana": "あかい",
    "romaji": "akai",
    "meaning": {
      "en": "red (adjective)",
      "fr": "rouge"
    },
    "level": "n5"
  },
  {
    "id": 8,
    "kanji": "秋",
    "kana": "あき",
    "romaji": "aki",
    "meaning": {
      "en": "fall (season)",
      "fr": "automne"
    },
    "level": "n5"
  },
  {
    "id": 13,
    "kanji": "朝御飯",
    "kana": "あさごはん",
    "romaji": "asagohan",
    "meaning": {
      "en": "breakfast",
      "fr": "petit déjeuner"
    },
    "level": "n5"
  },
  {
    "id": 14,
    "kanji": "明後日",
    "kana": "あさって",
    "romaji": "asatte",
    "meaning": {
      "en": "day after tomorrow",
      "fr": "après-demain"
    },
    "level": "n5"
  },
  {
    "id": 16,
    "kanji": "明日",
    "kana": "あした",
    "romaji": "ashita",
    "meaning": {
      "en": "tomorrow",
      "fr": "demain"
    },
    "level": "n5"
  },
  {
    "id": 19,
    "kanji": "暖かい",
    "kana": "あたたかい",
    "romaji": "atatakai",
    "meaning": {
      "en": "warm",
      "fr": "chaud"
    },
    "level": "n5"
  },
  {
    "id": 20,
    "kanji": "頭",
    "kana": "あたま",
    "romaji": "atama",
    "meaning": {
      "en": "head",
      "fr": "tête"
    },
    "level": "n5"
  },
  {
    "id": 24,
    "kanji": "熱い",
    "kana": "あつい",
    "romaji": "atsui",
    "meaning": {
      "en": "hot (objects)",
      "fr": "chaud (objet)"
    },
    "level": "n5"
  },
  {
    "id": 29,
    "kanji": "兄",
    "kana": "あに",
    "romaji": "ani",
    "meaning": {
      "en": "(my) older brother (humble)",
      "fr": "frère ainé"
    },
    "level": "n5"
  },
  {
    "id": 30,
    "kanji": "姉",
    "kana": "あね",
    "romaji": "ane",
    "meaning": {
      "en": "(my) older sister (humble)",
      "fr": "sœur aînée"
    },
    "level": "n5"
  },
  {
    "id": 37,
    "kanji": "雨",
    "kana": "あめ",
    "romaji": "ame",
    "meaning": {
      "en": "rain",
      "fr": "pluie"
    },
    "level": "n5"
  },
  {
    "id": 39,
    "kanji": "洗う",
    "kana": "あらう",
    "romaji": "arau",
    "meaning": {
      "en": "to wash",
      "fr": "laver"
    },
    "level": "n5"
  },
  {
    "id": 42,
    "kanji": "歩く",
    "kana": "あるく",
    "romaji": "aruku",
    "meaning": {
      "en": "to walk",
      "fr": "marcher"
    },
    "level": "n5"
  },
  {
    "id": 46,
    "kanji": "言う",
    "kana": "いう",
    "romaji": "iu",
    "meaning": {
      "en": "to say",
      "fr": "dire"
    },
    "level": "n5"
  },
  {
    "id": 47,
    "kanji": "家",
    "kana": "いえ",
    "romaji": "ie",
    "meaning": {
      "en": "house, home",
      "fr": "maison"
    },
    "level": "n5"
  },
  {
    "id": 54,
    "kanji": "椅子",
    "kana": "いす",
    "romaji": "isu",
    "meaning": {
      "en": "chair",
      "fr": "chaise"
    },
    "level": "n5"
  },
  {
    "id": 55,
    "kanji": "忙しい",
    "kana": "いそがしい",
    "romaji": "isogashii",
    "meaning": {
      "en": "busy (people, days)",
      "fr": "être occupé"
    },
    "level": "n5"
  },
  {
    "id": 57,
    "kanji": "一",
    "kana": "いち",
    "romaji": "ichi",
    "meaning": {
      "en": "one",
      "fr": "un"
    },
    "level": "n5"
  },
  {
    "id": 62,
    "kanji": "一緒",
    "kana": "いっしょ",
    "romaji": "issho",
    "meaning": {
      "en": "together",
      "fr": "ensemble"
    },
    "level": "n5"
  },
  {
    "id": 63,
    "kanji": "五つ",
    "kana": "いつつ",
    "romaji": "itsutsu",
    "meaning": {
      "en": "five things",
      "fr": "cinq"
    },
    "level": "n5"
  },
  {
    "id": 65,
    "kanji": "犬",
    "kana": "いぬ",
    "romaji": "inu",
    "meaning": {
      "en": "dog",
      "fr": "chien"
    },
    "level": "n5"
  },
  {
    "id": 68,
    "kanji": "妹",
    "kana": "いもうと",
    "romaji": "imouto",
    "meaning": {
      "en": "younger sister (humble)",
      "fr": "(ma) sœur cadette"
    },
    "level": "n5"
  },
  {
    "id": 72,
    "kanji": "要る",
    "kana": "いる",
    "romaji": "iru",
    "meaning": {
      "en": "to need",
      "fr": "avoir besoin"
    },
    "level": "n5"
  },
  {
    "id": 80,
    "kanji": "歌う",
    "kana": "うたう",
    "romaji": "utau",
    "meaning": {
      "en": "to sing",
      "fr": "chanter"
    },
    "level": "n5"
  },
  {
    "id": 729,
    "kanji": "苦い",
    "kana": "にがい",
    "romaji": "nigai",
    "meaning": {
      "en": "bitter",
      "fr": "amer"
    },
    "level": "n4"
  },
  {
    "id": 735,
    "kanji": "医学",
    "kana": "いがく",
    "romaji": "igaku",
    "meaning": {
      "en": "medical science",
      "fr": "médecine"
    },
    "level": "n4"
  },
  {
    "id": 752,
    "kanji": "大学生",
    "kana": "だいがくせい",
    "romaji": "daigakusei",
    "meaning": {
      "en": "college student, university student",
      "fr": "étudiant (université)"
    },
    "level": "n4"
  },
  {
    "id": 754,
    "kanji": "予習",
    "kana": "よしゅう",
    "romaji": "yoshuu",
    "meaning": {
      "en": "preparation of lessons (for class)",
      "fr": "préparation pour un cours"
    },
    "level": "n4"
  },
  {
    "id": 763,
    "kanji": "比べる",
    "kana": "くらべる",
    "romaji": "kuraberu",
    "meaning": {
      "en": "to compare",
      "fr": "comparer"
    },
    "level": "n4"
  },
  {
    "id": 766,
    "kanji": "郊外",
    "kana": "こうがい",
    "romaji": "kougai",
    "meaning": {
      "en": "suburb, outskirts",
      "fr": "banlieue"
    },
    "level": "n4"
  },
  {
    "id": 768,
    "kanji": "売り場",
    "kana": "うりば",
    "romaji": "uriba",
    "meaning": {
      "en": "place where things are sold",
      "fr": "lieu de vente"
    },
    "level": "n4"
  },
  {
    "id": 769,
    "kanji": "正月",
    "kana": "しょうがつ",
    "romaji": "shougatsu",
    "meaning": {
      "en": "New Year, New Year's Day",
      "fr": "le Nouvel An"
    },
    "level": "n4"
  },
  {
    "id": 772,
    "kanji": "発音",
    "kana": "はつおん",
    "romaji": "hatsuon",
    "meaning": {
      "en": "pronunciation",
      "fr": "prononciation"
    },
    "level": "n4"
  },
  {
    "id": 782,
    "kanji": "建てる",
    "kana": "たてる",
    "romaji": "tateru",
    "meaning": {
      "en": "to build",
      "fr": "construire"
    },
    "level": "n4"
  },
  {
    "id": 786,
    "kanji": "布団",
    "kana": "ふとん",
    "romaji": "futon",
    "meaning": {
      "en": "futon",
      "fr": "futon (sorte de matelas japonais)"
    },
    "level": "n4"
  },
  {
    "id": 792,
    "kanji": "台風",
    "kana": "たいふう",
    "romaji": "taifuu",
    "meaning": {
      "en": "typhoon",
      "fr": "typhon"
    },
    "level": "n4"
  },
  {
    "id": 796,
    "kanji": "通る",
    "kana": "とおる",
    "romaji": "tooru",
    "meaning": {
      "en": "to pass (by), to go through",
      "fr": "passer à travers"
    },
    "level": "n4"
  },
  {
    "id": 799,
    "kanji": "葉",
    "kana": "は",
    "romaji": "ha",
    "meaning": {
      "en": "leaf",
      "fr": "feuille"
    },
    "level": "n4"
  },
  {
    "id": 811,
    "kanji": "絹",
    "kana": "きぬ",
    "romaji": "kinu",
    "meaning": {
      "en": "silk",
      "fr": "soie"
    },
    "level": "n4"
  },
  {
    "id": 813,
    "kanji": "深い",
    "kana": "ふかい",
    "romaji": "fukai",
    "meaning": {
      "en": "deep, profound",
      "fr": "profond"
    },
    "level": "n4"
  },
  {
    "id": 825,
    "kanji": "致す",
    "kana": "いたす",
    "romaji": "itasu",
    "meaning": {
      "en": "-- extra-modest expression for する --",
      "fr": "faire"
    },
    "level": "n4"
  },
  {
    "id": 831,
    "kanji": "親",
    "kana": "おや",
    "romaji": "oya",
    "meaning": {
      "en": "a parent",
      "fr": "parents"
    },
    "level": "n4"
  },
  {
    "id": 847,
    "kanji": "季節",
    "kana": "きせつ",
    "romaji": "kisetsu",
    "meaning": {
      "en": "season (in reference to weather)",
      "fr": "saison"
    },
    "level": "n4"
  },
  {
    "id": 854,
    "kanji": "畳",
    "kana": "たたみ",
    "romaji": "tatami",
    "meaning": {
      "en": "tatami mat (Japanese straw mat)",
      "fr": "tatami"
    },
    "level": "n4"
  },
  {
    "id": 856,
    "kanji": "地理",
    "kana": "ちり",
    "romaji": "chiri",
    "meaning": {
      "en": "geography",
      "fr": "géographie"
    },
    "level": "n4"
  },
  {
    "id": 868,
    "kanji": "止める",
    "kana": "とめる",
    "romaji": "tomeru",
    "meaning": {
      "en": "to stop (something)",
      "fr": "arrêter (qqchose)"
    },
    "level": "n4"
  },
  {
    "id": 882,
    "kanji": "星",
    "kana": "ほし",
    "romaji": "hoshi",
    "meaning": {
      "en": "star",
      "fr": "étoile"
    },
    "level": "n4"
  },
  {
    "id": 892,
    "kanji": "再来月",
    "kana": "さらいげつ",
    "romaji": "saraigetsu",
    "meaning": {
      "en": "the month after next",
      "fr": "dans deux mois"
    },
    "level": "n4"
  },
  {
    "id": 1392,
    "kanji": "覚める",
    "kana": "さめる",
    "romaji": "sameru",
    "meaning": {
      "en": "to wake, to wake up",
      "fr": "se réveiller"
    },
    "level": "n3"
  },
  {
    "id": 1397,
    "kanji": "猿",
    "kana": "さる",
    "romaji": "saru",
    "meaning": {
      "en": "monkey",
      "fr": "singe"
    },
    "level": "n3"
  },
  {
    "id": 1402,
    "kanji": "酸性",
    "kana": "さんせい",
    "romaji": "sansei",
    "meaning": {
      "en": "acidity",
      "fr": "acidité"
    },
    "level": "n3"
  },
  {
    "id": 1403,
    "kanji": "酸素",
    "kana": "さんそ",
    "romaji": "sanso",
    "meaning": {
      "en": "oxygen",
      "fr": "oxygène"
    },
    "level": "n3"
  },
  {
    "id": 1409,
    "kanji": "四角",
    "kana": "しかく",
    "romaji": "shikaku",
    "meaning": {
      "en": "square (noun)",
      "fr": "carré"
    },
    "level": "n3"
  },
  {
    "id": 1412,
    "kanji": "四季",
    "kana": "しき",
    "romaji": "shiki",
    "meaning": {
      "en": "four seasons",
      "fr": "les quatre saisons"
    },
    "level": "n3"
  },
  {
    "id": 1419,
    "kanji": "資源",
    "kana": "しげん",
    "romaji": "shigen",
    "meaning": {
      "en": "resources",
      "fr": "ressources"
    },
    "level": "n3"
  },
  {
    "id": 1423,
    "kanji": "事実",
    "kana": "じじつ",
    "romaji": "jijitsu",
    "meaning": {
      "en": "fact, truth, reality",
      "fr": "un fait"
    },
    "level": "n3"
  },
  {
    "id": 1426,
    "kanji": "詩人",
    "kana": "しじん",
    "romaji": "shijin",
    "meaning": {
      "en": "poet",
      "fr": "poète"
    },
    "level": "n3"
  },
  {
    "id": 1429,
    "kanji": "自然",
    "kana": "しぜん",
    "romaji": "shizen",
    "meaning": {
      "en": "nature, spontaneous",
      "fr": "nature"
    },
    "level": "n3"
  },
  {
    "id": 1431,
    "kanji": "舌",
    "kana": "した",
    "romaji": "shita",
    "meaning": {
      "en": "tongue",
      "fr": "langue (anat.)"
    },
    "level": "n3"
  },
  {
    "id": 1436,
    "kanji": "質",
    "kana": "しつ",
    "romaji": "shitsu",
    "meaning": {
      "en": "quality, nature (of person)",
      "fr": "qualité"
    },
    "level": "n3"
  },
  {
    "id": 1438,
    "kanji": "湿気",
    "kana": "しっけ",
    "romaji": "shikke",
    "meaning": {
      "en": "moisture, humidity, dampness",
      "fr": "humidité"
    },
    "level": "n3"
  },
  {
    "id": 1446,
    "kanji": "実に",
    "kana": "じつに",
    "romaji": "jitsuni",
    "meaning": {
      "en": "indeed, truly, surely",
      "fr": "vraiment, en effet"
    },
    "level": "n3"
  },
  {
    "id": 1452,
    "kanji": "自動",
    "kana": "じどう",
    "romaji": "jidou",
    "meaning": {
      "en": "automatic, self-motion",
      "fr": "automatique"
    },
    "level": "n3"
  },
  {
    "id": 1453,
    "kanji": "児童",
    "kana": "じどう",
    "romaji": "jidou",
    "meaning": {
      "en": "children, juvenile",
      "fr": "enfant"
    },
    "level": "n3"
  },
  {
    "id": 1459,
    "kanji": "支払",
    "kana": "しはらい",
    "romaji": "shiharai",
    "meaning": {
      "en": "payment",
      "fr": "paiement"
    },
    "level": "n3"
  },
  {
    "id": 1460,
    "kanji": "支払う",
    "kana": "しはらう",
    "romaji": "shiharau",
    "meaning": {
      "en": "to pay",
      "fr": "payer"
    },
    "level": "n3"
  },
  {
    "id": 1462,
    "kanji": "資本",
    "kana": "しほん",
    "romaji": "shihon",
    "meaning": {
      "en": "funds, capital",
      "fr": "capitaux"
    },
    "level": "n3"
  },
  {
    "id": 1463,
    "kanji": "姉妹",
    "kana": "しまい",
    "romaji": "shimai",
    "meaning": {
      "en": "sisters",
      "fr": "sœurs"
    },
    "level": "n3"
  },
  {
    "id": 1474,
    "kanji": "週",
    "kana": "しゅう",
    "romaji": "shuu",
    "meaning": {
      "en": "week",
      "fr": "semaine"
    },
    "level": "n3"
  },
  {
    "id": 1479,
    "kanji": "宗教",
    "kana": "しゅうきょう",
    "romaji": "shuukyou",
    "meaning": {
      "en": "religion",
      "fr": "religion"
    },
    "level": "n3"
  },
  {
    "id": 1496,
    "kanji": "手術",
    "kana": "しゅじゅつ",
    "romaji": "shujutsu",
    "meaning": {
      "en": "surgical operation",
      "fr": "opération chirurgicale"
    },
    "level": "n3"
  },
  {
    "id": 1497,
    "kanji": "首相",
    "kana": "しゅしょう",
    "romaji": "shushou",
    "meaning": {
      "en": "Prime Minister",
      "fr": "Premier Ministre"
    },
    "level": "n3"
  },
  {
    "id": 3528,
    "kanji": "重役",
    "kana": "じゅうやく",
    "romaji": "juuyaku",
    "meaning": {
      "en": "director, high executive",
      "fr": "administrateur (de société)"
    },
    "level": "n2"
  },
  {
    "id": 3535,
    "kanji": "受験",
    "kana": "じゅけん",
    "romaji": "juken",
    "meaning": {
      "en": "taking an examination",
      "fr": "passer un examen"
    },
    "level": "n2"
  },
  {
    "id": 3536,
    "kanji": "主語",
    "kana": "しゅご",
    "romaji": "shugo",
    "meaning": {
      "en": "(gram) subject",
      "fr": "sujet"
    },
    "level": "n2"
  },
  {
    "id": 3539,
    "kanji": "述語",
    "kana": "じゅつご",
    "romaji": "jutsugo",
    "meaning": {
      "en": "predicate",
      "fr": "prédicat"
    },
    "level": "n2"
  },
  {
    "id": 3542,
    "kanji": "主役",
    "kana": "しゅやく",
    "romaji": "shuyaku",
    "meaning": {
      "en": "leading part",
      "fr": "rôle principal"
    },
    "level": "n2"
  },
  {
    "id": 3543,
    "kanji": "受話器",
    "kana": "じゅわき",
    "romaji": "juwaki",
    "meaning": {
      "en": "(telephone) receiver",
      "fr": "combiné (téléphone)"
    },
    "level": "n2"
  },
  {
    "id": 3545,
    "kanji": "巡査",
    "kana": "じゅんさ",
    "romaji": "junsa",
    "meaning": {
      "en": "policeman",
      "fr": "policier"
    },
    "level": "n2"
  },
  {
    "id": 3563,
    "kanji": "消化",
    "kana": "しょうか",
    "romaji": "shouka",
    "meaning": {
      "en": "digestion",
      "fr": "digestion"
    },
    "level": "n2"
  },
  {
    "id": 3564,
    "kanji": "小学生",
    "kana": "しょうがくせい",
    "romaji": "shougakusei",
    "meaning": {
      "en": "elementary school pupil",
      "fr": "élève d'école primaire"
    },
    "level": "n2"
  },
  {
    "id": 3566,
    "kanji": "将棋",
    "kana": "しょうぎ",
    "romaji": "shougi",
    "meaning": {
      "en": "Japanese chess",
      "fr": "shôgi (échecs japonais)"
    },
    "level": "n2"
  },
  {
    "id": 3567,
    "kanji": "蒸気",
    "kana": "じょうき",
    "romaji": "jouki",
    "meaning": {
      "en": "steam, vapor",
      "fr": "vapeur"
    },
    "level": "n2"
  },
  {
    "id": 3568,
    "kanji": "定規",
    "kana": "じょうぎ",
    "romaji": "jougi",
    "meaning": {
      "en": "(measuring) ruler",
      "fr": "règle à mesurer"
    },
    "level": "n2"
  },
  {
    "id": 3573,
    "kanji": "上下",
    "kana": "じょうげ",
    "romaji": "jouge",
    "meaning": {
      "en": "high and low, up and down",
      "fr": "haut et bas"
    },
    "level": "n2"
  },
  {
    "id": 3574,
    "kanji": "障子",
    "kana": "しょうじ",
    "romaji": "shouji",
    "meaning": {
      "en": "paper sliding door",
      "fr": "porte coulissante japonaise (en papier)"
    },
    "level": "n2"
  },
  {
    "id": 3575,
    "kanji": "商社",
    "kana": "しょうしゃ",
    "romaji": "shousha",
    "meaning": {
      "en": "trading company",
      "fr": "société de commerce"
    },
    "level": "n2"
  },
  {
    "id": 3576,
    "kanji": "乗車",
    "kana": "じょうしゃ",
    "romaji": "jousha",
    "meaning": {
      "en": "taking a train, entraining",
      "fr": "monter (en voiture, en train...)"
    },
    "level": "n2"
  },
  {
    "id": 3579,
    "kanji": "小数",
    "kana": "しょうすう",
    "romaji": "shousuu",
    "meaning": {
      "en": "fraction (part of), decimal",
      "fr": "fraction décimale"
    },
    "level": "n2"
  },
  {
    "id": 3587,
    "kanji": "小便",
    "kana": "しょうべん",
    "romaji": "shouben",
    "meaning": {
      "en": "(col) urine, piss",
      "fr": "urine"
    },
    "level": "n2"
  },
  {
    "id": 3588,
    "kanji": "消防署",
    "kana": "しょうぼうしょ",
    "romaji": "shoubousho",
    "meaning": {
      "en": "fire station",
      "fr": "caserne de pompiers"
    },
    "level": "n2"
  },
  {
    "id": 3589,
    "kanji": "正味",
    "kana": "しょうみ",
    "romaji": "shoumi",
    "meaning": {
      "en": "net (weight)",
      "fr": "net (poids)"
    },
    "level": "n2"
  },
  {
    "id": 3592,
    "kanji": "初級",
    "kana": "しょきゅう",
    "romaji": "shokyuu",
    "meaning": {
      "en": "elementary level",
      "fr": "niveau élémentaire"
    },
    "level": "n2"
  },
  {
    "id": 3593,
    "kanji": "助教授",
    "kana": "じょきょうじゅ",
    "romaji": "jokyouju",
    "meaning": {
      "en": "assistant professor",
      "fr": "professeur assistant"
    },
    "level": "n2"
  },
  {
    "id": 3595,
    "kanji": "食塩",
    "kana": "しょくえん",
    "romaji": "shokuen",
    "meaning": {
      "en": "table salt",
      "fr": "sel de table"
    },
    "level": "n2"
  },
  {
    "id": 3598,
    "kanji": "初旬",
    "kana": "しょじゅん",
    "romaji": "shojun",
    "meaning": {
      "en": "first 10 days of the month",
      "fr": "les 10 premiers jours du mois"
    },
    "level": "n2"
  },
  {
    "id": 5274,
    "kanji": "現像",
    "kana": "げんぞう",
    "romaji": "genzou",
    "meaning": {
      "en": "developing (film)",
      "fr": "développer (photographie)"
    },
    "level": "n1"
  },
  {
    "id": 5276,
    "kanji": "見地",
    "kana": "けんち",
    "romaji": "kenchi",
    "meaning": {
      "en": "point of view",
      "fr": "point de vue"
    },
    "level": "n1"
  },
  {
    "id": 5281,
    "kanji": "原爆",
    "kana": "げんばく",
    "romaji": "genbaku",
    "meaning": {
      "en": "atomic bomb",
      "fr": "bombe atomique"
    },
    "level": "n1"
  },
  {
    "id": 5286,
    "kanji": "原油",
    "kana": "げんゆ",
    "romaji": "gen'yu",
    "meaning": {
      "en": "crude oil",
      "fr": "huile non raffinée"
    },
    "level": "n1"
  },
  {
    "id": 5287,
    "kanji": "兼用",
    "kana": "けんよう",
    "romaji": "ken'you",
    "meaning": {
      "en": "multi-use, combined use",
      "fr": "usage combiné, polyvalent"
    },
    "level": "n1"
  },
  {
    "id": 5289,
    "kanji": "言論",
    "kana": "げんろん",
    "romaji": "genron",
    "meaning": {
      "en": "discussion, speech",
      "fr": "discussion"
    },
    "level": "n1"
  },
  {
    "id": 5298,
    "kanji": "工学",
    "kana": "こうがく",
    "romaji": "kougaku",
    "meaning": {
      "en": "engineering",
      "fr": "ingénieur"
    },
    "level": "n1"
  },
  {
    "id": 5300,
    "kanji": "合議",
    "kana": "ごうぎ",
    "romaji": "gougi",
    "meaning": {
      "en": "consultation, conference",
      "fr": "consultation, conférence"
    },
    "level": "n1"
  },
  {
    "id": 5301,
    "kanji": "皇居",
    "kana": "こうきょ",
    "romaji": "koukyo",
    "meaning": {
      "en": "Imperial Palace",
      "fr": "palais impérial"
    },
    "level": "n1"
  },
  {
    "id": 5303,
    "kanji": "鉱業",
    "kana": "こうぎょう",
    "romaji": "kougyou",
    "meaning": {
      "en": "mining industry",
      "fr": "industrie minière"
    },
    "level": "n1"
  },
  {
    "id": 5307,
    "kanji": "煌々と",
    "kana": "こうこうと",
    "romaji": "koukouto",
    "meaning": {
      "en": "brightly",
      "fr": "brillamment"
    },
    "level": "n1"
  },
  {
    "id": 5308,
    "kanji": "考古学",
    "kana": "こうこがく",
    "romaji": "koukogaku",
    "meaning": {
      "en": "archeology",
      "fr": "archéologie"
    },
    "level": "n1"
  },
  {
    "id": 5311,
    "kanji": "鉱山",
    "kana": "こうざん",
    "romaji": "kouzan",
    "meaning": {
      "en": "mine",
      "fr": "mine (minerai)"
    },
    "level": "n1"
  },
  {
    "id": 5312,
    "kanji": "講習",
    "kana": "こうしゅう",
    "romaji": "koushuu",
    "meaning": {
      "en": "short course, training",
      "fr": "public"
    },
    "level": "n1"
  },
  {
    "id": 5319,
    "kanji": "香辛料",
    "kana": "こうしんりょう",
    "romaji": "koushinryou",
    "meaning": {
      "en": "spices",
      "fr": "épices"
    },
    "level": "n1"
  },
  {
    "id": 5321,
    "kanji": "洪水",
    "kana": "こうずい",
    "romaji": "kouzui",
    "meaning": {
      "en": "flood",
      "fr": "inondation"
    },
    "level": "n1"
  },
  {
    "id": 5328,
    "kanji": "公団",
    "kana": "こうだん",
    "romaji": "koudan",
    "meaning": {
      "en": "public corporation",
      "fr": "corporation publique"
    },
    "level": "n1"
  },
  {
    "id": 5330,
    "kanji": "口頭",
    "kana": "こうとう",
    "romaji": "koutou",
    "meaning": {
      "en": "oral",
      "fr": "oral"
    },
    "level": "n1"
  },
  {
    "id": 5331,
    "kanji": "講読",
    "kana": "こうどく",
    "romaji": "koudoku",
    "meaning": {
      "en": "reading",
      "fr": "abonnement (pour un journal, magazine)"
    },
    "level": "n1"
  },
  {
    "id": 5332,
    "kanji": "購読",
    "kana": "こうどく",
    "romaji": "koudoku",
    "meaning": {
      "en": "subscription",
      "fr": "abonnement (pour un journal, magazine)"
    },
    "level": "n1"
  },
  {
    "id": 5339,
    "kanji": "公募",
    "kana": "こうぼ",
    "romaji": "koubo",
    "meaning": {
      "en": "public appeal, public contribution",
      "fr": "appel public"
    },
    "level": "n1"
  },
  {
    "id": 5342,
    "kanji": "小売",
    "kana": "こうり",
    "romaji": "kouri",
    "meaning": {
      "en": "retail",
      "fr": "vente au détail"
    },
    "level": "n1"
  },
  {
    "id": 5343,
    "kanji": "効率",
    "kana": "こうりつ",
    "romaji": "kouritsu",
    "meaning": {
      "en": "efficiency",
      "fr": "efficacité"
    },
    "level": "n1"
  },
  {
    "id": 5344,
    "kanji": "公立",
    "kana": "こうりつ",
    "romaji": "kouritsu",
    "meaning": {
      "en": "public institution",
      "fr": "publique (institution)"
    },
    "level": "n1"
  }
];

export function wordsByLevel(level: Level): SiteWord[] {
  return WORDS.filter((w) => w.level === level);
}
