// GENERATED by scripts/build-words.mjs — do not edit by hand.
// Source: the Yumo app's assets/word-data.json (7,972 records).
import type { Level } from './tokens';
import type { SiteWord } from './select-words';

export const WORDS: SiteWord[] = [
  {
    "id": 2,
    "kanji": "会う",
    "kana": "あう",
    "romaji": "au",
    "meaning": "to meet, to see",
    "level": "n5"
  },
  {
    "id": 3,
    "kanji": "青",
    "kana": "あお",
    "romaji": "ao",
    "meaning": "blue (noun)",
    "level": "n5"
  },
  {
    "id": 4,
    "kanji": "青い",
    "kana": "あおい",
    "romaji": "aoi",
    "meaning": "blue (adjective)",
    "level": "n5"
  },
  {
    "id": 5,
    "kanji": "赤",
    "kana": "あか",
    "romaji": "aka",
    "meaning": "red (noun)",
    "level": "n5"
  },
  {
    "id": 6,
    "kanji": "赤い",
    "kana": "あかい",
    "romaji": "akai",
    "meaning": "red (adjective)",
    "level": "n5"
  },
  {
    "id": 8,
    "kanji": "秋",
    "kana": "あき",
    "romaji": "aki",
    "meaning": "fall (season)",
    "level": "n5"
  },
  {
    "id": 9,
    "kanji": "開く",
    "kana": "あく",
    "romaji": "aku",
    "meaning": "to open, to become open",
    "level": "n5"
  },
  {
    "id": 10,
    "kanji": "開ける",
    "kana": "あける",
    "romaji": "akeru",
    "meaning": "to open (v.t.)",
    "level": "n5"
  },
  {
    "id": 11,
    "kanji": "上げる",
    "kana": "あげる",
    "romaji": "ageru",
    "meaning": "to raise, to lift",
    "level": "n5"
  },
  {
    "id": 12,
    "kanji": "朝",
    "kana": "あさ",
    "romaji": "asa",
    "meaning": "morning",
    "level": "n5"
  },
  {
    "id": 13,
    "kanji": "朝御飯",
    "kana": "あさごはん",
    "romaji": "asagohan",
    "meaning": "breakfast",
    "level": "n5"
  },
  {
    "id": 14,
    "kanji": "明後日",
    "kana": "あさって",
    "romaji": "asatte",
    "meaning": "day after tomorrow",
    "level": "n5"
  },
  {
    "id": 16,
    "kanji": "明日",
    "kana": "あした",
    "romaji": "ashita",
    "meaning": "tomorrow",
    "level": "n5"
  },
  {
    "id": 19,
    "kanji": "暖かい",
    "kana": "あたたかい",
    "romaji": "atatakai",
    "meaning": "warm",
    "level": "n5"
  },
  {
    "id": 20,
    "kanji": "頭",
    "kana": "あたま",
    "romaji": "atama",
    "meaning": "head",
    "level": "n5"
  },
  {
    "id": 21,
    "kanji": "新しい",
    "kana": "あたらしい",
    "romaji": "atarashii",
    "meaning": "new",
    "level": "n5"
  },
  {
    "id": 23,
    "kanji": "暑い",
    "kana": "あつい",
    "romaji": "atsui",
    "meaning": "hot (in reference to weather), warm",
    "level": "n5"
  },
  {
    "id": 24,
    "kanji": "熱い",
    "kana": "あつい",
    "romaji": "atsui",
    "meaning": "hot (objects)",
    "level": "n5"
  },
  {
    "id": 25,
    "kanji": "厚い",
    "kana": "あつい",
    "romaji": "atsui",
    "meaning": "kind, warm(hearted), thick, deep",
    "level": "n5"
  },
  {
    "id": 29,
    "kanji": "兄",
    "kana": "あに",
    "romaji": "ani",
    "meaning": "(my) older brother (humble)",
    "level": "n5"
  },
  {
    "id": 30,
    "kanji": "姉",
    "kana": "あね",
    "romaji": "ane",
    "meaning": "(my) older sister (humble)",
    "level": "n5"
  },
  {
    "id": 33,
    "kanji": "浴びる",
    "kana": "あびる",
    "romaji": "abiru",
    "meaning": "to bathe, to shower",
    "level": "n5"
  },
  {
    "id": 34,
    "kanji": "危ない",
    "kana": "あぶない",
    "romaji": "abunai",
    "meaning": "dangerous, critical",
    "level": "n5"
  },
  {
    "id": 35,
    "kanji": "甘い",
    "kana": "あまい",
    "romaji": "amai",
    "meaning": "generous, sweet",
    "level": "n5"
  },
  {
    "id": 719,
    "kanji": "踏む",
    "kana": "ふむ",
    "romaji": "fumu",
    "meaning": "to step on, to tread on",
    "level": "n4"
  },
  {
    "id": 723,
    "kanji": "大抵",
    "kana": "たいてい",
    "romaji": "taitei",
    "meaning": "generally, usually",
    "level": "n4"
  },
  {
    "id": 726,
    "kanji": "鳴る",
    "kana": "なる",
    "romaji": "naru",
    "meaning": "to sound, to ring (v.i.)",
    "level": "n4"
  },
  {
    "id": 728,
    "kanji": "生きる",
    "kana": "いきる",
    "romaji": "ikiru",
    "meaning": "to live",
    "level": "n4"
  },
  {
    "id": 729,
    "kanji": "苦い",
    "kana": "にがい",
    "romaji": "nigai",
    "meaning": "bitter",
    "level": "n4"
  },
  {
    "id": 730,
    "kanji": "沸く",
    "kana": "わく",
    "romaji": "waku",
    "meaning": "to boil, to grow hot",
    "level": "n4"
  },
  {
    "id": 731,
    "kanji": "意見",
    "kana": "いけん",
    "romaji": "iken",
    "meaning": "opinion, view, idea",
    "level": "n4"
  },
  {
    "id": 733,
    "kanji": "漫画",
    "kana": "まんが",
    "romaji": "manga",
    "meaning": "comic (book), cartoon",
    "level": "n4"
  },
  {
    "id": 735,
    "kanji": "医学",
    "kana": "いがく",
    "romaji": "igaku",
    "meaning": "medical science",
    "level": "n4"
  },
  {
    "id": 743,
    "kanji": "必ず",
    "kana": "かならず",
    "romaji": "kanarazu",
    "meaning": "surely, certainly",
    "level": "n4"
  },
  {
    "id": 744,
    "kanji": "壊す",
    "kana": "こわす",
    "romaji": "kowasu",
    "meaning": "to break, to break down",
    "level": "n4"
  },
  {
    "id": 746,
    "kanji": "床屋",
    "kana": "とこや",
    "romaji": "tokoya",
    "meaning": "barber's (shop)",
    "level": "n4"
  },
  {
    "id": 748,
    "kanji": "運動",
    "kana": "うんどうする",
    "romaji": "undousuru",
    "meaning": "exercise",
    "level": "n4"
  },
  {
    "id": 749,
    "kanji": "止む",
    "kana": "やむ",
    "romaji": "yamu",
    "meaning": "to cease, to stop",
    "level": "n4"
  },
  {
    "id": 752,
    "kanji": "大学生",
    "kana": "だいがくせい",
    "romaji": "daigakusei",
    "meaning": "college student, university student",
    "level": "n4"
  },
  {
    "id": 753,
    "kanji": "運転手",
    "kana": "うんてんしゅ",
    "romaji": "untenshu",
    "meaning": "driver (by occupation)",
    "level": "n4"
  },
  {
    "id": 754,
    "kanji": "予習",
    "kana": "よしゅう",
    "romaji": "yoshuu",
    "meaning": "preparation of lessons (for class)",
    "level": "n4"
  },
  {
    "id": 755,
    "kanji": "心配",
    "kana": "しんぱいする",
    "romaji": "shinpaisuru",
    "meaning": "worry, concern",
    "level": "n4"
  },
  {
    "id": 756,
    "kanji": "別",
    "kana": "べつ",
    "romaji": "betsu",
    "meaning": "distinction, different",
    "level": "n4"
  },
  {
    "id": 760,
    "kanji": "拾う",
    "kana": "ひろう",
    "romaji": "hirou",
    "meaning": "to pick up (something), to find",
    "level": "n4"
  },
  {
    "id": 762,
    "kanji": "気",
    "kana": "き",
    "romaji": "ki",
    "meaning": "spirit, mood",
    "level": "n4"
  },
  {
    "id": 763,
    "kanji": "比べる",
    "kana": "くらべる",
    "romaji": "kuraberu",
    "meaning": "to compare",
    "level": "n4"
  },
  {
    "id": 766,
    "kanji": "郊外",
    "kana": "こうがい",
    "romaji": "kougai",
    "meaning": "suburb, outskirts",
    "level": "n4"
  },
  {
    "id": 768,
    "kanji": "売り場",
    "kana": "うりば",
    "romaji": "uriba",
    "meaning": "place where things are sold",
    "level": "n4"
  },
  {
    "id": 1387,
    "kanji": "作法",
    "kana": "さほう",
    "romaji": "sahou",
    "meaning": "manners, etiquette, propriety",
    "level": "n3"
  },
  {
    "id": 1388,
    "kanji": "様々",
    "kana": "さまざま",
    "romaji": "samazama",
    "meaning": "varied, various",
    "level": "n3"
  },
  {
    "id": 1389,
    "kanji": "冷ます",
    "kana": "さます",
    "romaji": "samasu",
    "meaning": "to cool, to let cool",
    "level": "n3"
  },
  {
    "id": 1390,
    "kanji": "覚ます",
    "kana": "さます",
    "romaji": "samasu",
    "meaning": "to awaken",
    "level": "n3"
  },
  {
    "id": 1391,
    "kanji": "冷める",
    "kana": "さめる",
    "romaji": "sameru",
    "meaning": "to become cool, to wear off",
    "level": "n3"
  },
  {
    "id": 1392,
    "kanji": "覚める",
    "kana": "さめる",
    "romaji": "sameru",
    "meaning": "to wake, to wake up",
    "level": "n3"
  },
  {
    "id": 1394,
    "kanji": "皿",
    "kana": "さら",
    "romaji": "sara",
    "meaning": "plate, dish",
    "level": "n3"
  },
  {
    "id": 1395,
    "kanji": "更に",
    "kana": "さらに",
    "romaji": "sarani",
    "meaning": "furthermore, moreover",
    "level": "n3"
  },
  {
    "id": 1396,
    "kanji": "去る",
    "kana": "さる",
    "romaji": "saru",
    "meaning": "to leave, to go away",
    "level": "n3"
  },
  {
    "id": 1397,
    "kanji": "猿",
    "kana": "さる",
    "romaji": "saru",
    "meaning": "monkey",
    "level": "n3"
  },
  {
    "id": 1398,
    "kanji": "騒ぎ",
    "kana": "さわぎ",
    "romaji": "sawagi",
    "meaning": "uproar, disturbance",
    "level": "n3"
  },
  {
    "id": 1399,
    "kanji": "参加",
    "kana": "さんか",
    "romaji": "sanka",
    "meaning": "participation",
    "level": "n3"
  },
  {
    "id": 1400,
    "kanji": "参考",
    "kana": "さんこう",
    "romaji": "sankou",
    "meaning": "reference, consultation",
    "level": "n3"
  },
  {
    "id": 1401,
    "kanji": "賛成",
    "kana": "さんせい",
    "romaji": "sansei",
    "meaning": "approval, agreement",
    "level": "n3"
  },
  {
    "id": 1402,
    "kanji": "酸性",
    "kana": "さんせい",
    "romaji": "sansei",
    "meaning": "acidity",
    "level": "n3"
  },
  {
    "id": 1403,
    "kanji": "酸素",
    "kana": "さんそ",
    "romaji": "sanso",
    "meaning": "oxygen",
    "level": "n3"
  },
  {
    "id": 1404,
    "kanji": "氏",
    "kana": "し",
    "romaji": "shi",
    "meaning": "family name, lineage",
    "level": "n3"
  },
  {
    "id": 1406,
    "kanji": "幸せ",
    "kana": "しあわせ",
    "romaji": "shiawase",
    "meaning": "happiness, blessing",
    "level": "n3"
  },
  {
    "id": 1409,
    "kanji": "四角",
    "kana": "しかく",
    "romaji": "shikaku",
    "meaning": "square (noun)",
    "level": "n3"
  },
  {
    "id": 1410,
    "kanji": "直に",
    "kana": "じかに",
    "romaji": "jikani",
    "meaning": "immediately, readily, directly",
    "level": "n3"
  },
  {
    "id": 1412,
    "kanji": "四季",
    "kana": "しき",
    "romaji": "shiki",
    "meaning": "four seasons",
    "level": "n3"
  },
  {
    "id": 1413,
    "kanji": "直",
    "kana": "じき",
    "romaji": "jiki",
    "meaning": "immediately, soon, shortly",
    "level": "n3"
  },
  {
    "id": 1414,
    "kanji": "時期",
    "kana": "じき",
    "romaji": "jiki",
    "meaning": "time, season, period",
    "level": "n3"
  },
  {
    "id": 1415,
    "kanji": "支給",
    "kana": "しきゅう",
    "romaji": "shikyuu",
    "meaning": "payment, allowance",
    "level": "n3"
  },
  {
    "id": 3526,
    "kanji": "就任",
    "kana": "しゅうにん",
    "romaji": "shuunin",
    "meaning": "inauguration, assumption of office",
    "level": "n2"
  },
  {
    "id": 3527,
    "kanji": "周辺",
    "kana": "しゅうへん",
    "romaji": "shuuhen",
    "meaning": "circumference, peripheral",
    "level": "n2"
  },
  {
    "id": 3528,
    "kanji": "重役",
    "kana": "じゅうやく",
    "romaji": "juuyaku",
    "meaning": "director, high executive",
    "level": "n2"
  },
  {
    "id": 3529,
    "kanji": "終了",
    "kana": "しゅうりょう",
    "romaji": "shuuryou",
    "meaning": "end, close, termination",
    "level": "n2"
  },
  {
    "id": 3530,
    "kanji": "重量",
    "kana": "じゅうりょう",
    "romaji": "juuryou",
    "meaning": "heavyweight",
    "level": "n2"
  },
  {
    "id": 3531,
    "kanji": "重力",
    "kana": "じゅうりょく",
    "romaji": "juuryoku",
    "meaning": "gravity",
    "level": "n2"
  },
  {
    "id": 3532,
    "kanji": "熟語",
    "kana": "じゅくご",
    "romaji": "jukugo",
    "meaning": "idiom, kanji compound",
    "level": "n2"
  },
  {
    "id": 3533,
    "kanji": "祝日",
    "kana": "しゅくじつ",
    "romaji": "shukujitsu",
    "meaning": "national holiday",
    "level": "n2"
  },
  {
    "id": 3534,
    "kanji": "縮小",
    "kana": "しゅくしょう",
    "romaji": "shukushou",
    "meaning": "reduction, curtailment",
    "level": "n2"
  },
  {
    "id": 3535,
    "kanji": "受験",
    "kana": "じゅけん",
    "romaji": "juken",
    "meaning": "taking an examination",
    "level": "n2"
  },
  {
    "id": 3536,
    "kanji": "主語",
    "kana": "しゅご",
    "romaji": "shugo",
    "meaning": "(gram) subject",
    "level": "n2"
  },
  {
    "id": 3537,
    "kanji": "主人",
    "kana": "しゅじん",
    "romaji": "shujin",
    "meaning": "(one's own) husband",
    "level": "n2"
  },
  {
    "id": 3538,
    "kanji": "出勤",
    "kana": "しゅっきん",
    "romaji": "shukkin",
    "meaning": "going to work, at work",
    "level": "n2"
  },
  {
    "id": 3539,
    "kanji": "述語",
    "kana": "じゅつご",
    "romaji": "jutsugo",
    "meaning": "predicate",
    "level": "n2"
  },
  {
    "id": 3540,
    "kanji": "出張",
    "kana": "しゅっちょう",
    "romaji": "shutchou",
    "meaning": "official tour, business trip",
    "level": "n2"
  },
  {
    "id": 3541,
    "kanji": "寿命",
    "kana": "じゅみょう",
    "romaji": "jumyou",
    "meaning": "life span",
    "level": "n2"
  },
  {
    "id": 3542,
    "kanji": "主役",
    "kana": "しゅやく",
    "romaji": "shuyaku",
    "meaning": "leading part",
    "level": "n2"
  },
  {
    "id": 3543,
    "kanji": "受話器",
    "kana": "じゅわき",
    "romaji": "juwaki",
    "meaning": "(telephone) receiver",
    "level": "n2"
  },
  {
    "id": 3544,
    "kanji": "循環",
    "kana": "じゅんかん",
    "romaji": "junkan",
    "meaning": "circulation, rotation, cycle",
    "level": "n2"
  },
  {
    "id": 3545,
    "kanji": "巡査",
    "kana": "じゅんさ",
    "romaji": "junsa",
    "meaning": "policeman",
    "level": "n2"
  },
  {
    "id": 3546,
    "kanji": "順々",
    "kana": "じゅんじゅん",
    "romaji": "junjun",
    "meaning": "in order, in turn",
    "level": "n2"
  },
  {
    "id": 3547,
    "kanji": "順序",
    "kana": "じゅんじょ",
    "romaji": "junjo",
    "meaning": "order, sequence, procedure",
    "level": "n2"
  },
  {
    "id": 3548,
    "kanji": "純情",
    "kana": "じゅんじょう",
    "romaji": "junjou",
    "meaning": "pure heart",
    "level": "n2"
  },
  {
    "id": 3549,
    "kanji": "純粋",
    "kana": "じゅんすい",
    "romaji": "junsui",
    "meaning": "pure, genuine, unmixed",
    "level": "n2"
  },
  {
    "id": 5274,
    "kanji": "現像",
    "kana": "げんぞう",
    "romaji": "genzou",
    "meaning": "developing (film)",
    "level": "n1"
  },
  {
    "id": 5275,
    "kanji": "原則",
    "kana": "げんそく",
    "romaji": "gensoku",
    "meaning": "principle, general rule",
    "level": "n1"
  },
  {
    "id": 5276,
    "kanji": "見地",
    "kana": "けんち",
    "romaji": "kenchi",
    "meaning": "point of view",
    "level": "n1"
  },
  {
    "id": 5277,
    "kanji": "現地",
    "kana": "げんち",
    "romaji": "genchi",
    "meaning": "actual place, local",
    "level": "n1"
  },
  {
    "id": 5278,
    "kanji": "限定",
    "kana": "げんてい",
    "romaji": "gentei",
    "meaning": "limit, restriction",
    "level": "n1"
  },
  {
    "id": 5279,
    "kanji": "原点",
    "kana": "げんてん",
    "romaji": "genten",
    "meaning": "origin (coordinates, starting point)",
    "level": "n1"
  },
  {
    "id": 5280,
    "kanji": "原典",
    "kana": "げんてん",
    "romaji": "genten",
    "meaning": "original, source",
    "level": "n1"
  },
  {
    "id": 5281,
    "kanji": "原爆",
    "kana": "げんばく",
    "romaji": "genbaku",
    "meaning": "atomic bomb",
    "level": "n1"
  },
  {
    "id": 5282,
    "kanji": "原文",
    "kana": "げんぶん",
    "romaji": "genbun",
    "meaning": "the text, original",
    "level": "n1"
  },
  {
    "id": 5283,
    "kanji": "厳密",
    "kana": "げんみつ",
    "romaji": "genmitsu",
    "meaning": "strict, close",
    "level": "n1"
  },
  {
    "id": 5284,
    "kanji": "賢明",
    "kana": "けんめい",
    "romaji": "kenmei",
    "meaning": "wisdom, intelligence, prudence",
    "level": "n1"
  },
  {
    "id": 5285,
    "kanji": "倹約",
    "kana": "けんやく",
    "romaji": "ken'yaku",
    "meaning": "thrift, economy, frugality",
    "level": "n1"
  },
  {
    "id": 5286,
    "kanji": "原油",
    "kana": "げんゆ",
    "romaji": "gen'yu",
    "meaning": "crude oil",
    "level": "n1"
  },
  {
    "id": 5287,
    "kanji": "兼用",
    "kana": "けんよう",
    "romaji": "ken'you",
    "meaning": "multi-use, combined use",
    "level": "n1"
  },
  {
    "id": 5288,
    "kanji": "権力",
    "kana": "けんりょく",
    "romaji": "kenryoku",
    "meaning": "(political) power, authority, influence",
    "level": "n1"
  },
  {
    "id": 5289,
    "kanji": "言論",
    "kana": "げんろん",
    "romaji": "genron",
    "meaning": "discussion, speech",
    "level": "n1"
  },
  {
    "id": 5291,
    "kanji": "語彙",
    "kana": "ごい",
    "romaji": "goi",
    "meaning": "vocabulary, glossary",
    "level": "n1"
  },
  {
    "id": 5292,
    "kanji": "恋する",
    "kana": "こいする",
    "romaji": "koisuru",
    "meaning": "to fall in love with, to love",
    "level": "n1"
  },
  {
    "id": 5295,
    "kanji": "好意",
    "kana": "こうい",
    "romaji": "koui",
    "meaning": "good will, favor, courtesy",
    "level": "n1"
  },
  {
    "id": 5296,
    "kanji": "行為",
    "kana": "こうい",
    "romaji": "koui",
    "meaning": "act, deed, conduct",
    "level": "n1"
  },
  {
    "id": 5298,
    "kanji": "工学",
    "kana": "こうがく",
    "romaji": "kougaku",
    "meaning": "engineering",
    "level": "n1"
  },
  {
    "id": 5299,
    "kanji": "抗議",
    "kana": "こうぎ",
    "romaji": "kougi",
    "meaning": "protest, objection",
    "level": "n1"
  },
  {
    "id": 5300,
    "kanji": "合議",
    "kana": "ごうぎ",
    "romaji": "gougi",
    "meaning": "consultation, conference",
    "level": "n1"
  },
  {
    "id": 5301,
    "kanji": "皇居",
    "kana": "こうきょ",
    "romaji": "koukyo",
    "meaning": "Imperial Palace",
    "level": "n1"
  }
];

export function wordsByLevel(level: Level): SiteWord[] {
  return WORDS.filter((w) => w.level === level);
}
