// Generates lib/words.ts from the Yumo app's dataset. Run manually with
// `npm run build:words`; the output is committed so `npm run build` never
// needs the app repo checked out beside this one.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../Yumo/assets/word-data.json');
const OUT = resolve(here, '../lib/words.ts');
const PER_LEVEL = 24;

const LEVELS = ['n5', 'n4', 'n3', 'n2', 'n1'];

// Mirrors selectWords in lib/select-words.ts. Duplicated because a plain ESM
// script cannot import the TypeScript module; both copies are pinned by tests
// (select-words.test.ts and words.test.ts), so a drift fails `npm test`.
// Both rendered locales must be usable, or French cards fall back to English.
// Words the app should absolutely still teach — they are real JLPT
// vocabulary — but which should never land on a marketing page, where a
// visitor meets them with no context and no reason to expect them. This is a
// display concern, not a dataset one: nothing is removed from the app.
const NOT_FOR_DISPLAY = new Set(['自殺']);

const usable = (g) => !!g && g.length > 0 && g.length < 40 && !g.includes(';');

function selectWords(raw, perLevel) {
  const out = [];
  for (const level of LEVELS) {
    const picked = raw
      .filter((w) => w.level === level)
      .filter((w) => w.kanji.length >= 1 && w.kanji.length <= 3)
      .filter((w) => usable(w.meaning?.en) && usable(w.meaning?.fr))
      .filter((w) => w.kanji !== w.kana)
      .filter((w) => !w.kanji.includes('～') && !w.kanji.includes('〜'))
      .filter((w) => !NOT_FOR_DISPLAY.has(w.kanji))
      .slice(0, perLevel)
      .map((w) => ({
        id: w.id, kanji: w.kanji, kana: w.kana, romaji: w.romaji,
        meaning: { en: w.meaning.en, fr: w.meaning.fr }, level: w.level,
      }));
    out.push(...picked);
  }
  return out;
}

const data = JSON.parse(readFileSync(SOURCE, 'utf8'));
const words = selectWords(data.words, PER_LEVEL);

for (const level of LEVELS) {
  const n = words.filter((w) => w.level === level).length;
  if (n < PER_LEVEL) {
    throw new Error(`only ${n} usable words for ${level}, expected ${PER_LEVEL}`);
  }
}

const body = `// GENERATED by scripts/build-words.mjs — do not edit by hand.
// Source: the Yumo app's assets/word-data.json (7,972 records).
import type { Level } from './tokens';
import type { SiteWord } from './select-words';

export const WORDS: SiteWord[] = ${JSON.stringify(words, null, 2)};

export function wordsByLevel(level: Level): SiteWord[] {
  return WORDS.filter((w) => w.level === level);
}
`;

writeFileSync(OUT, body, 'utf8');
console.log(`wrote ${words.length} words to lib/words.ts`);
