// Generates lib/words.ts from the Yumo app's dataset. Run manually with
// `npm run build:words`; the output is committed so `npm run build` never
// needs the app repo checked out beside this one.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../Yumo/assets/word-data.json');
const OUT = resolve(here, '../lib/words.ts');
const PER_LEVEL = 24;

const LEVELS = ['n5', 'n4', 'n3', 'n2', 'n1'];

// Mirrors selectWords in lib/select-words.ts. Duplicated because a plain ESM
// script cannot import the TypeScript module; both copies are pinned by tests
// (select-words.test.ts and words.test.ts), so a drift fails `npm test`.
function selectWords(raw, perLevel) {
  const out = [];
  for (const level of LEVELS) {
    const picked = raw
      .filter((w) => w.level === level)
      .filter((w) => w.kanji.length >= 1 && w.kanji.length <= 3)
      .filter((w) => {
        const en = w.meaning?.en ?? '';
        return en.length > 0 && en.length < 40 && !en.includes(';');
      })
      .filter((w) => w.kanji !== w.kana)
      .filter((w) => !w.kanji.includes('～') && !w.kanji.includes('〜'))
      .slice(0, perLevel)
      .map((w) => ({
        id: w.id, kanji: w.kanji, kana: w.kana,
        romaji: w.romaji, meaning: w.meaning.en, level: w.level,
      }));
    out.push(...picked);
  }
  return out;
}

const data = JSON.parse(readFileSync(SOURCE, 'utf8'));
const words = selectWords(data.words, PER_LEVEL);

for (const level of LEVELS) {
  const n = words.filter((w) => w.level === level).length;
  if (n < PER_LEVEL) {
    throw new Error(`only ${n} usable words for ${level}, expected ${PER_LEVEL}`);
  }
}

const body = `// GENERATED by scripts/build-words.mjs — do not edit by hand.
// Source: the Yumo app's assets/word-data.json (7,972 records).
import type { Level } from './tokens';
import type { SiteWord } from './select-words';

export const WORDS: SiteWord[] = ${JSON.stringify(words, null, 2)};

export function wordsByLevel(level: Level): SiteWord[] {
  return WORDS.filter((w) => w.level === level);
}
`;

writeFileSync(OUT, body, 'utf8');
console.log(`wrote ${words.length} words to lib/words.ts`);
