// Generates the JLPT reference tables in lib/jlpt/ from the app's dataset.
// Run manually with `npm run build:jlpt`; the output is committed so a normal
// build never needs the app repo checked out beside this one — the same
// arrangement as build-words.mjs.
//
// This is a different job from build-words.mjs, which picks 24 words per level
// to decorate the landing page. Here the point is completeness: the whole
// level, in dictionary order, because a reference someone arrives at from
// "JLPT N5 vocabulary list" is only worth having if nothing is missing.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = resolve(here, '../../Yumo/assets/word-data.json');
const OUT_DIR = resolve(here, '../lib/jlpt');

const LEVELS = process.argv.slice(2).length ? process.argv.slice(2) : ['n5'];

// Gojūon rows, the order a Japanese dictionary uses. Voiced and small kana sit
// with the row they are formed from, so ぎ files under か and ゃ under や —
// which is what a reader scanning for a word expects.
const ROWS = [
  ['あ', 'あぁいぃうぅえぇおぉ'],
  ['か', 'かがきぎくぐけげこご'],
  ['さ', 'さざしじすずせぜそぞ'],
  ['た', 'ただちぢっつづてでとど'],
  ['な', 'なにぬねの'],
  ['は', 'はばぱひびぴふぶぷへべぺほぼぽ'],
  ['ま', 'まみむめも'],
  ['や', 'やゃゆゅよょ'],
  ['ら', 'らりるれろ'],
  ['わ', 'わをん'],
];

// Readings in the dataset are not always bare kana: counters and suffixes carry
// a wave dash (～円), and some entries annotate the particle they take
// ((〜を) とお). Filing those under the dash rather than their first real kana
// buries them at the end of the page, away from the word a reader is scanning
// for. Strip the notation before deciding the row — but keep it for display,
// where it is the thing that marks the entry as a suffix.
function sortKana(kana) {
  return (kana || '')
    .replace(/[～〜]/g, '')
    .replace(/\([^)]*\)/g, '')
    .replace(/\s+/g, '')
    // Loanwords are written in katakana (アパート, カメラ) and are a large part of N5.
    // A Japanese dictionary files them by the same reading as their hiragana
    // equivalents, so fold the block down before filing. Display keeps the
    // katakana — it is how the word is actually written.
    .replace(/[ァ-ヶ]/g, (c) => String.fromCharCode(c.charCodeAt(0) - 0x60))
    .trim();
}

const unfiled = [];

function row(kana) {
  const first = [...sortKana(kana)][0];
  for (const [label, members] of ROWS) if (members.includes(first)) return label;
  unfiled.push(kana);
  return null;
}

// The dataset carries JMdict's full gloss, which for some entries is a stack of
// senses separated by semicolons. Two senses is plenty of signal in a table
// cell; beyond that the row stops being scannable and the page reads as a data
// dump rather than a reference.
function gloss(en) {
  const senses = en
    .split(';')
    .map((s) => s.trim())
    .filter(Boolean);
  const kept = senses.slice(0, 2).join('; ');
  return kept.length > 80 ? senses[0] : kept;
}

const raw = JSON.parse(readFileSync(SOURCE, 'utf8'));
const rows = Array.isArray(raw) ? raw : Object.values(raw).find(Array.isArray);

mkdirSync(OUT_DIR, { recursive: true });

for (const level of LEVELS) {
  const words = rows
    .filter((w) => w.level === level)
    .filter((w) => w.kanji && w.kana && w.meaning?.en)
    .map((w) => ({
      kanji: w.kanji,
      kana: w.kana,
      romaji: w.romaji,
      en: gloss(w.meaning.en),
      row: row(w.kana),
    }))
    .filter((w) => w.en.length > 0 && w.row !== null)
    // Dictionary order, by reading. localeCompare with 'ja' puts the kana in
    // gojūon sequence rather than code-point order, which interleaves voiced
    // and unvoiced forms incorrectly.
    .sort((a, b) => sortKana(a.kana).localeCompare(sortKana(b.kana), 'ja'));

  const upper = level.toUpperCase();
  const body = `// GENERATED by scripts/build-jlpt.mjs — do not edit by hand.
// Source: the Yumo app's assets/word-data.json, level ${level} (${words.length} records).
//
// Glosses are JMdict/EDICT (EDRDG) under CC BY-SA 4.0, credited on the page
// that renders them.
import type { JlptWord } from './types';

export const ${upper}_WORDS: JlptWord[] = ${JSON.stringify(words, null, 0)};
`;

  writeFileSync(resolve(OUT_DIR, `${level}.ts`), body);
  const bytes = Buffer.byteLength(body);
  console.log(
    `lib/jlpt/${level}.ts  ${words.length} words, ${(bytes / 1024).toFixed(0)} kB`,
  );
  if (unfiled.length) {
    // Loud rather than silently swept into a fallback row: an unfiled reading
    // means the kana table above has a gap worth looking at.
    console.warn(`  ${unfiled.length} unfiled reading(s):`, unfiled.slice(0, 8).join(' '));
    unfiled.length = 0;
  }
}
