// Converts the App Store captures into web-weight WebP plus an inline blur
// placeholder. Run with `npm run build:assets`; output is committed.
//
// This exists because next.config.ts sets output:'export' with
// images:{unoptimized:true} — Next cannot compress at request time, so
// whatever sits in public/ is exactly what every visitor downloads.
import { mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, '../../Yumo/store-screenshots/ios-6.9');
const OUT = resolve(here, '../public/shots');
const GEN = resolve(here, '../lib/shots.ts');

const MAP = {
  '01-today.png': 'today',
  '02-browse.png': 'browse',
  '03-saved.png': 'saved',
  '04-settings.png': 'settings',
  '05-widget-home.png': 'widgetHome',
};

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });

const entries = {};

// The Home Screen capture carries iOS's default rainbow wallpaper, which
// fights the site's beige ground. We cannot retake it (that needs a Mac), so
// the wallpaper is desaturated and lifted while the Yumo widget itself is
// composited back at full strength — the widget must stay the focal point,
// and a flat desaturation drains its green along with everything else.
// Bounds were measured from the source, not guessed.
const WIDGET_RECT = { left: 89, top: 296, width: 519, height: 518 };
const WIDGET_RADIUS = 96;

async function softenWallpaper(input) {
  const mask = Buffer.from(
    `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDGET_RECT.width}" height="${WIDGET_RECT.height}">` +
      `<rect width="${WIDGET_RECT.width}" height="${WIDGET_RECT.height}" ` +
      `rx="${WIDGET_RADIUS}" ry="${WIDGET_RADIUS}" fill="#fff"/></svg>`,
  );

  const widget = await sharp(input)
    .extract(WIDGET_RECT)
    .composite([{ input: mask, blend: 'dest-in' }])
    .png()
    .toBuffer();

  // Composite at full resolution and resize in a second pass: sharp applies
  // resize before composite within one pipeline regardless of call order, so
  // chaining them would paste the widget at source scale onto a shrunk base.
  return sharp(input)
    .modulate({ saturation: 0.26, brightness: 1.16 })
    .composite([{ input: widget, left: WIDGET_RECT.left, top: WIDGET_RECT.top }])
    .png()
    .toBuffer();
}

for (const [file, key] of Object.entries(MAP)) {
  const original = resolve(SRC, file);
  const meta = await sharp(original).metadata();
  const input = key === 'widgetHome' ? await softenWallpaper(original) : original;

  // The phones render at ~320 CSS px, so 1080 already covers a 3x display.
  // Shipping the 1290 source width cost 580 KB for pixels nothing shows.
  await sharp(input).resize(1080).webp({ quality: 78 }).toFile(resolve(OUT, `${key}.webp`));
  await sharp(input).resize(540).webp({ quality: 76 }).toFile(resolve(OUT, `${key}@small.webp`));

  const blurBuf = await sharp(input).resize(12).webp({ quality: 40 }).toBuffer();

  const scale = 1080 / meta.width;

  entries[key] = {
    src: `/shots/${key}.webp`,
    srcSmall: `/shots/${key}@small.webp`,
    width: 1080,
    height: Math.round(meta.height * scale),
    blur: `data:image/webp;base64,${blurBuf.toString('base64')}`,
  };
}

// A visitor downloads ONE variant per image — <picture> picks the small set
// on phones or the large set on desktop, never both. Summing the directory
// would charge the budget for bytes nobody transfers, so measure the worst
// case a single visitor actually pays.
const bytes = (suffix) =>
  readdirSync(OUT)
    .filter((f) => (suffix ? f.includes('@small') : !f.includes('@small')))
    .reduce((n, f) => n + statSync(resolve(OUT, f)).size, 0);

const large = bytes(false);
const small = bytes(true);
const total = Math.max(large, small);

const body = `// GENERATED by scripts/optimise-assets.mjs — do not edit by hand.
export interface Shot {
  src: string;
  srcSmall: string;
  width: number;
  height: number;
  blur: string;
}

export const SHOTS: Record<string, Shot> = ${JSON.stringify(entries, null, 2)};
`;

writeFileSync(GEN, body, 'utf8');
console.log(
  `wrote ${Object.keys(entries).length} shots — ` +
    `desktop ${(large / 1024).toFixed(0)} KB, mobile ${(small / 1024).toFixed(0)} KB`,
);

if (total > 400 * 1024) {
  throw new Error(
    `worst-case visitor payload ${(total / 1024).toFixed(0)} KB, budget is 400 KB`,
  );
}
